### ISSUE TITLE
Lock the navigation drawer in hidden position when signup and logon fragments are shown

### ISSUE THREAD

**Issue by guslong** [ERNICommunity/idea-board-android#10]

**Comment by guslong** [comment]
this is a bugger...!

**Comment by elgrangrifon45** [comment]
http://stackoverflow.com/questions/19439320/disabling-navigation-drawer-toggling-home-button-up-indicator-in-fragments

Might this help?

**Comment by guslong** [comment]
Fixed. Yes the stackoverflow post was helpful here.
What is important is that the xml file that contains the view for the navigation drawer has the following gravity property set:
`android:layout_gravity="start"
`
Then you need to disable swipe to open like this:
`drawerLayout.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED, Gravity.START);`
But that doesn't disable the "up" arrow (caret) on the action bar.
But that is easy...
This is how to turn off the "up" button on action bar:
`
ActionBar actionBar = getActionBar();
if (actionBar != null) {
    actionBar.setHomeButtonEnabled(false); // disable the button
    actionBar.setDisplayHomeAsUpEnabled(false); // remove the left caret
    actionBar.setDisplayShowHomeEnabled(false); // remove the icon
}
`

**Comment by guslong** [comment]
This was premature. Apparently the navigation drawer stays locked, so when we go to another fragment that should have the navigation drawer we need to undo all that.
